version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    networks:
      application:
        aliases:
          - 'application.local'

  webapp:
    build:
      context: .
      dockerfile: docker/webapp/Dockerfile
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM start_with_request=true var_display_max_depth=-1 max_nesting_level=3000 client_host=docker.for.mac.localhost
      - PHP_IDE_CONFIG=serverName=application.local
      - XDEBUG_MODE=develop,debug,coverage
    volumes:
      - .:/var/www/html
    networks:
      - application

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/opt/pgdata
      - POSTGRES_DB=application
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/opt/pgdata
    networks:
      - application

  node:
    image: node:latest
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app

networks:
  application:
    driver: "bridge"

volumes:
  postgresdata:
    "driver": "local"
