services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8099:80
      - 8100:443
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    networks:
      aspirepress-cdn:
      application:
        aliases:
          - 'cdn.aspirepress.local'


  webapp:
    build:
      context: .
      dockerfile: docker/webapp/Dockerfile
      target: devphp
    volumes:
      - .:/var/www/html
    env_file:
      - .env.dist
      - .env
    networks:
      - aspirepress-cdn
      - application

  redis:
    image: redis:latest
    networks:
      - aspirepress-cdn

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/opt/pgdata
      - POSTGRES_DB=aspirepress_cdn
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/opt/pgdata
    networks:
      - aspirepress-cdn
      - application

networks:
  application:
    driver: "bridge"
    name: wp-services
    external: true
  aspirepress-cdn:
    name: aspirepress-cdn
    driver: bridge

volumes:
  postgresdata:
    "driver": "local"
